### ISSUE TITLE
[web-server] auth changes

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#806]
#### TODOs:
* [x] Generate a jwt token when a user uses a strategy (mozilla-auth0, github) in web-server.
* [x] Return a taskcluster token (jwt) and an expiration time when using a strategy to login

Nits:
* [x] Remove `api.sso.mozilla.com` from the `audience` config and `taskcluster-credentials` from `scope`. I don't think we need this anymore.  We will not need `audience` or `scopes` config for mozilla-auth0 at all anymore (no need for an audience at all, and scopes can be hard-coded to `openid profile`)
* [x] Do not decode jwt in [`getPersonApi()`](https://github.com/taskcluster/taskcluster/blob/master/services/web-server/src/login/strategies/mozilla-auth0.js). Use the `expires_in` directly that we get from the `/oauth/token` endpoint.
* [x] Remove `window.opener.location` from [`callback.ejs`](https://github.com/taskcluster/taskcluster/blob/master/services/web-server/src/views/callback.ejs). Use rootUrl instead.

**Comment by djmitche** [comment]
I modified the first nit slightly.

**Comment by helfi92** [comment]
@djmitche Would you recommend the private signing key to be stored as an environment variable?

**Comment by djmitche** [comment]
I think it should be service config -- that's what we do for, for example, crypto keys for Azure tables.

**Comment by djmitche** [comment]
Is this finished?

**Comment by helfi92** [comment]
Indeed.
